-- Haskell data types for the abstract syntax.
-- Generated by the BNF converter.

{-# LANGUAGE GeneralizedNewtypeDeriving #-}

-- | The abstract syntax of language CCS.

module AbsCCS where

import Prelude (String)
import qualified Prelude as C (Eq, Ord, Show, Read)
import qualified Data.String

data Action = Output Label | Input Label
  deriving (C.Eq, C.Ord, C.Show, C.Read)

newtype Identifier = Identifier String
  deriving (C.Eq, C.Ord, C.Show, C.Read, Data.String.IsString)

newtype Label = Label String
  deriving (C.Eq, C.Ord, C.Show, C.Read, Data.String.IsString)

